### ISSUE TITLE
train.py throws errors

### ISSUE THREAD

**Issue by jalajm** [abskjha/face_alignment_keras#1]
Hi,

I was trying to run the keras implementation of the facial alignment code and trying to train a model using the 300W-LP dataset, but for some reason, I keep getting errors in the 'train.py' file.

I had to change the 'model.py' file and replace all 'merge' lines with concatenate (because apparently keras has stopped merge). For eg: In line 57, I had to replace:

'out = merge([merge1,residual], mode = 'sum', concat_axis = 1)'
with
'out = Concatenate(axis=1)([merge1,residual])'

Following this, I ran the 'train.py' script. After printing the complete CNN, it throws this error.

![Error](https://user-images.githubusercontent.com/20763855/60999195-8eb8b600-a328-11e9-82f2-1ba08c493a0b.JPG)

At this point, I'm not sure what is the solution to running the script for training the data. It would be great if you could help with this!

Thanks!

**Comment by abskjha** [comment]
Hi,
Please verify the keras and python versions with that in the readme. You need to create a directory 'saved_models' to save the models.

**Comment by qiqi7788** [comment]
hi，when I run this. In the convolution block, an error occurs, can you tell me how to solve it?

error：
Traceback (most recent call last):
  File "train.py", line 86, in <module>
    cb = FAN(x,4)
  File "E:\landmark_new\test\done\face_alignment_keras-master\model.py", line 164, in FAN
    conv2 = ConvBlock(act1,64, 128)
  File "E:\landmark_new\test\done\face_alignment_keras-master\model.py", line 52, in ConvBlock
    merge1 = Concatenate(axis=1)([conv1,conv2,conv3])
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\keras\backend\tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "E:\Anaconda3\envs\tensorflow\lib\site-packages\keras\layers\merge.py", line 362, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 2, 128, 64), (None, 2, 128, 32), (None, 2, 128, 32)]

**Comment by devvikas** [comment]
merge1 = Concatenate(axis=3)([conv1, conv2, conv3])

Try this on line # 52
@qiqi7788
